# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Peixin You
title: PhD Candidate
email: peixin.you.b2019@alumni.polytechnique.org

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  hyleindex
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# linkedin_username: Peixin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Peixin You is a bachelor student in Ecole Polytechnique

  I am most skilled in: <mark>Coq</mark> and <mark>Agda</mark>

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Ecole Polytechnique
        caption: 2019 - 2022(Expected)
        sub_title: BSc Mathematics and Computer Science
        quote: >
          The school was established in 1794 by the mathematician Gaspard Monge during the French Revolution, and it was once previously a military academy under Napoleon I in 1804. The institution is still supervised by the French Ministry of Defence.
        description: | # this will include new lines to allow paragraphs
          GPA : 4.15/4.0

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Some examples of higher inductive types
        link: github.com/hyleIndex/AIHoTT
        # link_text: Project Website
        additional_links:
          - title:  AIHoTT
            icon: fa-file-pdf-o
            url: https://github.com/hyleIndex/AIHoTT/blob/main/paper/paper.pdf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        description: | # this will include new lines to allow paragraphs
          Homotopy type theory is a theory axiomatize equality and also links type theory with geometry. In HoTT, types are interpreted as spaces. In HoTT we could generate the idea of inductive type to higher inductive by allowing define constructor to construct equalities. Here, we define and study higher inductive types in order to present some well-known and useful types and implement it in cubical Agda. We define integers as a HIT and show that it forms an Abelian group when equipped with addition. We also introduce two different definitions of the notion of free group on a set and show that they are equivalent. Finally, study two HIT definitions of symmetric groups: the "natural" one (which corresponds to the standard presentation by transpositions) and one which correspond to some "normal form" for symmetries, called Lehmer codes. We construct a map from the later to the former, and conjecture that it is part of an equivalence.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INRIA
        link: 
        # link_text: boringcompany.com
        sub_title: Reseach internship
        caption: Jan. 2022 - Present
        description: | # this will include new lines to allow paragraphs
            The goal of this project is to analyse the syntax and the semantics of the Faust programming language, which is dedicated to sound synthesis and audio processing with a strong focus on the design of synthesizers, musical instruments, audio effects, etc. The aim to get a better understanding of the categorical properties of the language by comparing it to well-known constructions such as cartesian closed categories and variants.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in formal method and logic some of my other interests and hobbies are:
      - Climbing
      - Photograhing
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
