# Theme Configuration
avatar: /images/avatar.jpg
favicon: /images/favicon.ico

# Menu Configuration
menu:
  - name: Publications
    url: /publications/
    icon: ai ai-google-scholar
  - name: Projects
    url: /projects/
    icon: fas fa-project-diagram
  - name: CV
    url: /CV/
    icon: fas fa-id-card
  - name: Talks
    url: /talks/
    icon: fas fa-microphone
  - name: Contact
    url: /contact/
    icon: fas fa-envelope

# CV Download
cv:
  download_link: https://www.nature.com/articles/d41586-025-01882-7.pdf # Optional: use a file in your repository but not an online link.

# About
about:
  I am a PhD student at Yale university supervised by Zhong Shao. My research interest lies in quantum computing, formal verfication, concurrency and logic. 

# Academic Profiles
academic_profiles:
  google_scholar: https://scholar.google.com/citations?user=vSzBfk4AAAAJ&hl=en
  orcid: https://orcid.org/0009-0002-8035-5209
  # researchgate: https://www.researchgate.net/profile/YOUR_ID
  github: https://github.com/hyleindex
  linkedin: https://linkedin.com/in/YOUR_ID

# Contact
contact:
  email: hyleindex@gmail.com
  # phone: "+0 123 456789"
  address: "Room 310, AKW, Yale University, New Haven, CT 06510, USA"
  # google_map: "https://maps.app.goo.gl/xxxxxxxxxxx"
  # office_hours: "Mon–Fri 10:00–16:00"

# Push/Ab
# Google adsense
# google_adsense: your_google_adsense_id
# Umami
# umami_id: your_umami_id
# Baidu_tongji
# baidu_tongji: your_baidu_tongji_id

# daisyui themes
daisyui:
  default: cupcake
  enabled:
    - light
    - dark
    - cupcake
    - bumblebee
    - emerald
    - corporate
    - synthwave
    - retro
    - cyberpunk
    - valentine
    - halloween
    - garden
    - forest
    - aqua
    - lofi
    - pastel
    - fantasy
    - wireframe
    - black
    - luxury
    - dracula
    - cmyk
    - autumn
    - business
    - acid
    - lemonade
    - night
    - coffee
    - winter
    - dim
    - nord
    - sunset
    - caramellatte
    - abyss
    - silk